title: atreyasha.github.io - Atreya Shankar
front: Occasional thoughts
author: Atreya Shankar
github: https://github.com/atreyasha

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/atreyasha"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/atreya-shankar-644352113"

urls:
    - text: PGP Public Key
      url: "https://pgp.mit.edu/pks/lookup?search=0x41723204DC79DDCDA43B80C35330BD3D1107E5A6&op=vindex"
    - text: XML Feed
      url: /sitemap.xml

url: "https://atreyasha.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
usemathjax: true
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
