title: atreyasha.github.io - Atreya Shankar
front: Occasional thoughts
author: Atreya Shankar
github: https://github.com/atreyasha

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/atreyasha"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/atreya-shankar-644352113"
    - icon: fa-university
      link: "https://www.hslu.ch/en/lucerne-university-of-applied-sciences-and-arts/about-us/people-finder/profile/?pid=5181"

urls:
    - text: PGP Public Key
      url: "https://github.com/atreyasha.gpg"
    - text: XML Feed
      url: /sitemap.xml

url: "https://atreyasha.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
usemathjax: true
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
